<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INR8,239.80INR8,239.80List Price INR10,_d7495c</name>
   <tag></tag>
   <elementGuidId>4b61c4f3-bd2e-409c-83e7-78b26bd56e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceOHrFsACikvZTGpdPIITYRg']/div[2]/div/ul/li[2]/span/a/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaf9e247-f80a-4649-979b-b67befc479a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-section</value>
      <webElementGuid>b41b723d-d54f-439c-be6f-0e501626a701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INR 8,239.80INR8,239.80List Price: INR 10,771.23INR10,771.23</value>
      <webElementGuid>2cd53b74-e807-4fbb-bc93-8344c686cfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-6&quot;)/div[@id=&quot;CardInstanceOHrFsACikvZTGpdPIITYRg&quot;]/div[@id=&quot;CardInstanceOHrFsACikvZTGpdPIITYRg&quot;]/div[@class=&quot;a-section a-spacing-none a-spacing-top-small feed-carousel hovering&quot;]/div[@class=&quot;a-section feed-carousel-viewport&quot;]/ul[@class=&quot;a-unordered-list a-nostyle a-horizontal feed-carousel-shelf _deals-shoveler-v2_style_list__pjYuB&quot;]/li[@class=&quot;feed-carousel-card _deals-shoveler-v2_style_dealCard__1HqkZ _deals-shoveler-v2_style_dealCardMinHeight__3YZz0&quot;]/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-link-normal a-text-normal&quot;]/div[@class=&quot;a-section _deals-shoveler-v2_style_dealInfo__1U5R1&quot;]/div[@class=&quot;a-row a-spacing-none&quot;]/div[@class=&quot;a-section&quot;]</value>
      <webElementGuid>d195aa13-0fd9-429b-ae28-0d1d59bfb1fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceOHrFsACikvZTGpdPIITYRg']/div[2]/div/ul/li[2]/span/a/div[2]/div[2]/div</value>
      <webElementGuid>52b7eebe-a8ab-42b9-af6d-f17d66aaa367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deal'])[21]/following::div[2]</value>
      <webElementGuid>3d877ded-ff9f-4f38-9619-79f5eef0fe40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% off'])[23]/following::div[3]</value>
      <webElementGuid>9e59aeee-8cce-473d-8a77-aa2d19bee11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/ul/li[2]/span/a/div[2]/div[2]/div</value>
      <webElementGuid>0cd51de1-0588-4c22-a952-630040c8fdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'INR 8,239.80INR8,239.80List Price: INR 10,771.23INR10,771.23' or . = 'INR 8,239.80INR8,239.80List Price: INR 10,771.23INR10,771.23')]</value>
      <webElementGuid>3f52acc8-b4b4-42a3-b135-072c8534b13a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
