<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Added to Cart_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>dad42c8a-7594-41ac-8152-0b373f571d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>623e2e23-6567-4526-be74-212c35288d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d8571c5e-ca42-4085-af7f-a76e94208aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>4d8b971e-54a8-4f77-8df7-ec9880d03507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;B0BZFLPFZJ&quot;]</value>
      <webElementGuid>5ebdc115-7239-4827-985c-f082456ecca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>60c2527e-12d8-4a37-ad7e-326e28f53748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b8d88e96-aac7-4b05-9885-3076a4bd611a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>exports_top_sellers_rec_d_sccl_1_atc_a</value>
      <webElementGuid>4130d991-be51-4298-8a12-f3d2c36af4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=exports_top_sellers_rec_d_sccl_1_atc_a?_encoding=UTF8&amp;pd_rd_i=B0BZFLPFZJ&amp;pd_rd_w=ujt9y&amp;content-id=amzn1.sym.f8a72df2-7490-43b5-abe7-4c1d4b8319fe&amp;pf_rd_p=f8a72df2-7490-43b5-abe7-4c1d4b8319fe&amp;pf_rd_r=4ZJQRJBT08AVEM5419JR&amp;pd_rd_wg=y6691&amp;pd_rd_r=5560f9ce-e44e-42ad-a747-dece25e6ff64</value>
      <webElementGuid>55f23d25-ec93-4e00-969d-41a01bc3b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>547a4211-b049-49ee-8c88-7122f16f3da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>aef47aca-97e5-452b-b799-97aa8c48c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>4b263294-c7b6-4c4c-97bf-2a53eb89d8de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>d5c4a8af-6b74-472d-bcd7-72346e32578b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>171d8c8c-2e0d-4656-a545-141de13af3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>58674dfd-b3bc-4172-b7a0-b7bfa724b02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>646612ae-535c-4cff-a58f-8bc041fc86ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
