<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Added to Cart_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>da5ee1d4-3ee0-42b9-a15a-afe45d36b393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d74291d-3f04-4764-aef2-36690435abcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fe4930ec-6377-4deb-84eb-9af451d4b11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>ce4b973b-f2ee-4021-8ebb-7a6c4b40fd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;B0BZFLPFZJ&quot;]</value>
      <webElementGuid>85ac8967-6af1-4656-9dab-56a63705b925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>c6ef1268-3407-4f92-a6c8-a9c71dac597f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0bbea3a6-fcb2-477d-92c5-d4c3967053bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>exports_top_sellers_rec_d_sccl_1_atc_a</value>
      <webElementGuid>a4cab0ea-966d-4bbb-8677-83b73aeed635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=exports_top_sellers_rec_d_sccl_1_atc_a?_encoding=UTF8&amp;pd_rd_i=B0BZFLPFZJ&amp;pd_rd_w=mv8fO&amp;content-id=amzn1.sym.f8a72df2-7490-43b5-abe7-4c1d4b8319fe&amp;pf_rd_p=f8a72df2-7490-43b5-abe7-4c1d4b8319fe&amp;pf_rd_r=ZBE1ZMBE3MJD5G7B88H2&amp;pd_rd_wg=YeH5b&amp;pd_rd_r=f1d7b27e-72bf-4153-9283-922a39f128d7</value>
      <webElementGuid>007ad80a-311d-4269-ae52-2c87af0161e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>09636f68-59c2-4260-acb4-9409301aee73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>4d0095ff-5266-4a41-bcfb-484089cd7c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>4fa8b767-4fc5-4145-90ce-934e165ef5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>c2c1093a-a2b4-4370-96f7-78aeb73c9dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>1cd31edf-ea74-4b25-9554-a9d6029f29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>ce28e0a7-86e6-46b3-b5b7-0a5cf08e0648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>36dbf3ed-a4be-40cc-a51d-ee1c2ac17baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
