<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>9b33539e-4134-4c76-8104-05b9e8988d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hm-icon-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d6fc172-3c88-482c-be46-e4ce51e6bc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hm-icon-label</value>
      <webElementGuid>84a60974-4d76-46c9-b4b5-55759dedc58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>cbdb3316-1ebc-4f2a-ac93-fa2e09971890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)/span[@class=&quot;hm-icon-label&quot;]</value>
      <webElementGuid>0ba7e964-75ce-4e9c-b274-24ed520c90c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']/span</value>
      <webElementGuid>e071b4da-48ff-4dd4-955d-00c374c6bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::span[1]</value>
      <webElementGuid>7181a04c-1251-40c9-81b6-fbd42c91fb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch Accounts'])[1]/following::span[2]</value>
      <webElementGuid>1a835bdd-a196-4e2e-8575-6122257fd052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Today', &quot;'&quot;, 's Deals')])[1]/preceding::span[1]</value>
      <webElementGuid>8ea8012d-cfe4-4a6c-a1fa-ae7299dd6721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Again'])[1]/preceding::span[1]</value>
      <webElementGuid>e3b0799d-0402-4c6a-a92a-a138d3d6c279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/span</value>
      <webElementGuid>061edf2b-e958-4516-a653-70900d9700b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>ba6dabf5-74e9-41b5-b929-0e08bac6e14e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
