<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Marieswarn, 94, karivalam, SANKARANKO_4f6f68</name>
   <tag></tag>
   <elementGuidId>841a02ae-d8f0-48f1-ad9b-c1923858db55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address-ui-widgets-saveOriginalOrSuggestedAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address-ui-widgets-saveOriginalOrSuggestedAddress&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13d86f02-5347-4f62-92d0-af34763f8998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-saveOriginalOrSuggestedAddress</value>
      <webElementGuid>d392afbd-a127-4366-83f5-bdd917923f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>a161ef0a-bbb0-417a-af31-2741490b1ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>61461591-0cc9-4426-b453-e3ae20932db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressFormContainer&quot;)/span[@class=&quot;a-declarative&quot;]/span[@class=&quot;a-button a-spacing-medium a-button-primary a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>9ab1ac9f-cbb7-4d7f-beaf-de1637ca9ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address-ui-widgets-saveOriginalOrSuggestedAddress']</value>
      <webElementGuid>bee86ca3-e2f1-4061-b8e5-829f7888b763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/span/span/span/input</value>
      <webElementGuid>775ba1e9-4686-476a-86b3-7138b43677e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/span/input</value>
      <webElementGuid>211a7d1a-24d3-42ee-87e1-35aaafed4fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'address-ui-widgets-saveOriginalOrSuggestedAddress' and @type = 'submit']</value>
      <webElementGuid>b0106920-2f4e-49d6-b70d-b34f2a0cad6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
