<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maries, 94, karivalam, SANKARANKOIL, _9b4776</name>
   <tag></tag>
   <elementGuidId>281ece6f-2ccf-4c4f-8dc1-92ebc9830841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address-ui-widgets-saveOriginalOrSuggestedAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address-ui-widgets-saveOriginalOrSuggestedAddress&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2cf3b48-c38e-4ff6-922a-8c0c110bacbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address-ui-widgets-saveOriginalOrSuggestedAddress</value>
      <webElementGuid>67de45ad-45a7-4437-bdde-732d4852a70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>f31c9afd-9063-4bb7-9115-a8ed3fc86b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4de83420-fbfd-412d-856f-17c7305cd2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressFormContainer&quot;)/span[@class=&quot;a-declarative&quot;]/span[@class=&quot;a-button a-spacing-medium a-button-primary a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>47c4cb20-d67b-45a4-8867-5ff4467e0561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address-ui-widgets-saveOriginalOrSuggestedAddress']</value>
      <webElementGuid>e50c507f-050c-42e9-a6fd-2dcb1a808464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/span/span/span/input</value>
      <webElementGuid>ed838758-add9-4ca0-b494-68a1d6428453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/span/input</value>
      <webElementGuid>fbee8c61-2c0b-4c0f-a804-ab184f7c1a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'address-ui-widgets-saveOriginalOrSuggestedAddress' and @type = 'submit']</value>
      <webElementGuid>01f6de27-1564-4d05-bad7-e5d5d0de8016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
