<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This order contains a gift_proceedToR_057b5e</name>
   <tag></tag>
   <elementGuidId>9ce41cde-bc85-496b-be22-097ef1179145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='proceedToRetailCheckout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;proceedToRetailCheckout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bce99d8-2168-40fe-b9cf-867880e4d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceedToRetailCheckout</value>
      <webElementGuid>0cb57b7e-34f5-40b2-b2b0-a07eaf92ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-id</name>
      <type>Main</type>
      <value>proceed-to-checkout-action</value>
      <webElementGuid>6accc75a-5ba2-4403-b4f0-32fb857fb71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>6527a17a-376f-4ae7-8b35-eda81403ceda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cc108c36-fd9a-4828-9e5b-7e3fa50c2b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed to checkout</value>
      <webElementGuid>f2424607-6a22-44e2-8028-a057a53319a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sc-buy-box-ptc-button-announce</value>
      <webElementGuid>ade6b9fb-86c2-4fe9-9251-9f79f9f63c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-ptc-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>37558045-2b2c-4c1c-979c-cf50174d2c9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='proceedToRetailCheckout']</value>
      <webElementGuid>e9458594-fa24-4973-ba85-e780694517eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sc-buy-box-ptc-button']/span/input</value>
      <webElementGuid>c4016fde-dded-49d4-b078-fb6e1edc7841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>15a66a22-7a55-4eec-9288-09635b0c1aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceedToRetailCheckout' and @type = 'submit']</value>
      <webElementGuid>9b6601fb-a956-425d-9c44-1ddef0a66403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
