<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Computer mice__fluid-quad-image-label-v_1bd5c6</name>
   <tag></tag>
   <elementGuidId>e1244470-fe10-4590-afea-2842bc0d5e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstancefrJY6LeMdM0QQbmZNGVbww']/div[2]/div[2]/div[2]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-section._fluid-quad-image-label-v2_style_gridRowTwo__15woW > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_quadrantContainer__3TMqG._fluid-quad-image-label-v2_style_rightQuadrant__PI01n > a.a-link-normal._fluid-quad-image-label-v2_style_centerImage__30wh-.aok-block.image-window > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr > img._fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK._fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06b3d96a-69f2-4e88-888a-f2912a46ae93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Chairs</value>
      <webElementGuid>e7fb1134-32df-469f-a925-6ee62dc89a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_1x._SY116_CB667159060_.jpg</value>
      <webElementGuid>ef7bda2c-4094-4072-aed9-df7f6b86e8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>85c50f50-fbfe-4908-9e41-d507abb7ae83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_2x._SY232_CB667159060_.jpg</value>
      <webElementGuid>f7fca30c-edc9-4de0-b001-970cd5923324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstancefrJY6LeMdM0QQbmZNGVbww&quot;)/div[@class=&quot;_fluid-quad-image-label-v2_style_fluidQuadImageLabelBody__3tld0&quot;]/div[@class=&quot;a-section _fluid-quad-image-label-v2_style_gridRowTwo__15woW&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_quadrantContainer__3TMqG _fluid-quad-image-label-v2_style_rightQuadrant__PI01n&quot;]/a[@class=&quot;a-link-normal _fluid-quad-image-label-v2_style_centerImage__30wh- aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>b8ed764f-f405-44b0-940f-fcd638a876bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstancefrJY6LeMdM0QQbmZNGVbww']/div[2]/div[2]/div[2]/a/div/img</value>
      <webElementGuid>26f2aeb8-2e38-4be4-8947-e7aeee2b0015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Chairs']</value>
      <webElementGuid>4ec5fb7d-9b58-4872-a333-063ce310bb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/div/img</value>
      <webElementGuid>2e65b35f-155c-43db-a5f7-c16945eca02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Chairs' and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_1x._SY116_CB667159060_.jpg']</value>
      <webElementGuid>7a011dfd-32bb-48a1-b3c3-7c8e18e4c1f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
