<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Update_submit.save-for-later.ac746a9c_0a36af</name>
   <tag></tag>
   <elementGuidId>6f16c3f3-149a-4101-baac-195d40b8f097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.save-for-later.ac746a9c-ba65-4eb2-87e4-a1e5977862a6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.save-for-later.ac746a9c-ba65-4eb2-87e4-a1e5977862a6&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0e63db4-9a2a-4586-a1b9-a105e3895772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.save-for-later.ac746a9c-ba65-4eb2-87e4-a1e5977862a6</value>
      <webElementGuid>537ad2b7-efed-49c0-9d02-aefca68e4fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save for later</value>
      <webElementGuid>70e626c4-ab38-4be4-b93d-97ab9c002126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>save-for-later</value>
      <webElementGuid>e75fb0cc-36f4-43f5-a173-2a58c2863132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save for later Bulldoglogy Carbon Black XL Puppy Pee Pads with Adhesive Sticky Tape - Extra Large Charcoal Housebreaking Dog Training Wee Pads (24x35) (40-Count, Black)</value>
      <webElementGuid>aa8e1e09-bcbf-4a94-b15e-eaa85f9cc7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3090832f-7f41-4a6d-933d-bbfd88e0c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>1a94a775-8d73-4958-8807-254bbfbda47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-ac746a9c-ba65-4eb2-87e4-a1e5977862a6&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-save-for-later&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>9544eba6-513e-4425-ae70-4085ee4e5b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.save-for-later.ac746a9c-ba65-4eb2-87e4-a1e5977862a6']</value>
      <webElementGuid>3722fd34-2c34-4765-ac35-4c4c803abc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-ac746a9c-ba65-4eb2-87e4-a1e5977862a6']/div[4]/div/div[3]/div/span[3]/span/input</value>
      <webElementGuid>f17d9151-2aed-4fcd-aa09-f8244167accc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/input</value>
      <webElementGuid>d511ccf0-1458-4145-a1b7-8cca465ade5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.save-for-later.ac746a9c-ba65-4eb2-87e4-a1e5977862a6' and @type = 'submit']</value>
      <webElementGuid>3389a2bc-42c4-4979-9f86-75bf10a1c17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
