<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Most wished for in Movies  TV_product-image</name>
   <tag></tag>
   <elementGuidId>49a02756-1b10-42fa-a6d4-4f7bd21ce036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='70b13a78-890b-4823-bcf7-11491e36692a']/div[2]/div/ul/li/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a37865a-a260-4fdb-b5cb-794f79ea2ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Oppenheimer - 4K Ultra HD + Blu-ray + Digital [4K UHD]</value>
      <webElementGuid>71d1358f-0591-4479-9cff-0886e06e671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/81QXIa9fFvL._AC_SY200_.jpg</value>
      <webElementGuid>c3147eb8-e38c-422f-bb49-b9cb37ae4248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>c0f36b6c-0a0a-45d2-aa7b-fb51eea9994d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200px</value>
      <webElementGuid>0b525fbe-161a-443a-8294-eada569e2697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/81QXIa9fFvL._AC_SY400_.jpg</value>
      <webElementGuid>b8be7d64-0b8f-4dd3-8939-0196809e991c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;70b13a78-890b-4823-bcf7-11491e36692a&quot;)/div[@class=&quot;a-section a-spacing-none feed-carousel first-carousel hovering&quot;]/div[@class=&quot;a-section feed-carousel-viewport&quot;]/ul[@class=&quot;a-unordered-list a-nostyle a-horizontal feed-carousel-shelf&quot;]/li[@class=&quot;feed-carousel-card&quot;]/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-link-normal&quot;]/img[@class=&quot;product-image&quot;]</value>
      <webElementGuid>5b2d6443-ed28-4971-b3de-abe516f67e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='70b13a78-890b-4823-bcf7-11491e36692a']/div[2]/div/ul/li/span/a/img</value>
      <webElementGuid>e1cf7a75-fb0b-4a1e-ace3-e04c21a066d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Oppenheimer - 4K Ultra HD + Blu-ray + Digital [4K UHD]']</value>
      <webElementGuid>be948dee-a095-489e-a34c-4870ded362d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>89a92441-e00c-41e9-9ce4-48201557fe28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Oppenheimer - 4K Ultra HD + Blu-ray + Digital [4K UHD]' and @src = 'https://m.media-amazon.com/images/I/81QXIa9fFvL._AC_SY200_.jpg']</value>
      <webElementGuid>9fbc7d63-5020-45e6-9f2f-c4013368bda6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
